import { Inter } from 'next/font/google'
import './globals.css'
import Context from './components/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Context>
      <html lang="en">
        <body className={inter.className}>
          <main>{children}</main>
          </body>
      </html>
    </Context>
  )
}
